### ISSUE TITLE
"皰"疹 文字問題

### ISSUE THREAD

**Issue by pofeng** [kiang/data.fda.gov.tw#1]
http://drugs.olc.tw/drugs/view/549293ea-a8b4-4009-8c26-1cffd38a10d1
適應症   單純？疹性角膜炎

已回報至
http://data.fda.gov.tw/frontsite/data/DataAction.do?method=doDetail&infoId=36

**Comment by kiang** [comment]
後來發現還蠻多類似情況的
http://drugs.olc.tw/drugs/index/%EF%BC%9F

**Comment by pofeng** [comment]
剛剛收到回信說改好了, 繼續回報所有的問號 :p

**Comment by yuger** [comment]
您的這個repository有60+GB吧？真是太大了.... @kiang

**Comment by kiang** [comment]
@yuger 就因為太大所以已經放棄治療 XD

已經切割成幾個
- 單純的資料集 -> https://github.com/kiang/data.fda.gov.tw-list
- 網頁爬蟲 -> https://github.com/kiang/tfda_license

原本的想法是把所有的藥物關聯檔案都備份起來，但資料量真的有些太大

另外，如果想要問的部份跟原本的 issue 無關建議另外開一個，而不是在不相關的 issue 討論
